# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/raphael/dev/heartbeat_pomodoro

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/raphael/dev/heartbeat_pomodoro

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/raphael/dev/heartbeat_pomodoro/CMakeFiles /Users/raphael/dev/heartbeat_pomodoro/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/raphael/dev/heartbeat_pomodoro/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named led_lib

# Build rule for target.
led_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 led_lib
.PHONY : led_lib

# fast build rule for target.
led_lib/fast:
	$(MAKE) -f CMakeFiles/led_lib.dir/build.make CMakeFiles/led_lib.dir/build
.PHONY : led_lib/fast

#=============================================================================
# Target rules for targets named uno_core_lib

# Build rule for target.
uno_core_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uno_core_lib
.PHONY : uno_core_lib

# fast build rule for target.
uno_core_lib/fast:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/build
.PHONY : uno_core_lib/fast

#=============================================================================
# Target rules for targets named heartbeat_pomo

# Build rule for target.
heartbeat_pomo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heartbeat_pomo
.PHONY : heartbeat_pomo

# fast build rule for target.
heartbeat_pomo/fast:
	$(MAKE) -f CMakeFiles/heartbeat_pomo.dir/build.make CMakeFiles/heartbeat_pomo.dir/build
.PHONY : heartbeat_pomo/fast

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.c.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.c.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.c.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.c.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.c.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.c.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.c.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.c.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.c.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.c.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.c.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.c.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.c.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.c.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.c.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.c.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.c.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.c.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.c.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.c.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.c.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.c.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.c.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.c.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.cpp.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.cpp.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.cpp.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.cpp.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.cpp.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.cpp.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.cpp.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.cpp.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.cpp.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.cpp.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.cpp.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.cpp.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.c.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.c.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.c.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.c.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.c.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.c.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.c.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.c.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.c.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.c.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.c.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.c.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.c.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.c.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.c.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.c.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.c.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.c.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.c.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.c.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.c.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.c.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.c.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.c.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.c.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.c.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.c.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.c.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.c.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.c.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.c.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.c.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.c.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.c.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.c.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.c.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.c.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.c.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.c.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.c.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.c.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.c.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.c.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.c.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.c.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.c.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.c.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.c.s

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.obj: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.c.obj

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.obj

# target to build an object file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.c.obj:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.c.obj
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.c.obj

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.i: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.c.i

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.i

# target to preprocess a source file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.c.i:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.c.i
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.c.i

Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.s: Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.c.s

.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.s

# target to generate assembly for a file
Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.c.s:
	$(MAKE) -f CMakeFiles/uno_core_lib.dir/build.make CMakeFiles/uno_core_lib.dir/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.c.s
.PHONY : Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.c.s

headway_demo.obj: headway_demo.cpp.obj

.PHONY : headway_demo.obj

# target to build an object file
headway_demo.cpp.obj:
	$(MAKE) -f CMakeFiles/heartbeat_pomo.dir/build.make CMakeFiles/heartbeat_pomo.dir/headway_demo.cpp.obj
.PHONY : headway_demo.cpp.obj

headway_demo.i: headway_demo.cpp.i

.PHONY : headway_demo.i

# target to preprocess a source file
headway_demo.cpp.i:
	$(MAKE) -f CMakeFiles/heartbeat_pomo.dir/build.make CMakeFiles/heartbeat_pomo.dir/headway_demo.cpp.i
.PHONY : headway_demo.cpp.i

headway_demo.s: headway_demo.cpp.s

.PHONY : headway_demo.s

# target to generate assembly for a file
headway_demo.cpp.s:
	$(MAKE) -f CMakeFiles/heartbeat_pomo.dir/build.make CMakeFiles/heartbeat_pomo.dir/headway_demo.cpp.s
.PHONY : headway_demo.cpp.s

neopixel/Adafruit_NeoPixel.obj: neopixel/Adafruit_NeoPixel.cpp.obj

.PHONY : neopixel/Adafruit_NeoPixel.obj

# target to build an object file
neopixel/Adafruit_NeoPixel.cpp.obj:
	$(MAKE) -f CMakeFiles/led_lib.dir/build.make CMakeFiles/led_lib.dir/neopixel/Adafruit_NeoPixel.cpp.obj
.PHONY : neopixel/Adafruit_NeoPixel.cpp.obj

neopixel/Adafruit_NeoPixel.i: neopixel/Adafruit_NeoPixel.cpp.i

.PHONY : neopixel/Adafruit_NeoPixel.i

# target to preprocess a source file
neopixel/Adafruit_NeoPixel.cpp.i:
	$(MAKE) -f CMakeFiles/led_lib.dir/build.make CMakeFiles/led_lib.dir/neopixel/Adafruit_NeoPixel.cpp.i
.PHONY : neopixel/Adafruit_NeoPixel.cpp.i

neopixel/Adafruit_NeoPixel.s: neopixel/Adafruit_NeoPixel.cpp.s

.PHONY : neopixel/Adafruit_NeoPixel.s

# target to generate assembly for a file
neopixel/Adafruit_NeoPixel.cpp.s:
	$(MAKE) -f CMakeFiles/led_lib.dir/build.make CMakeFiles/led_lib.dir/neopixel/Adafruit_NeoPixel.cpp.s
.PHONY : neopixel/Adafruit_NeoPixel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... led_lib"
	@echo "... uno_core_lib"
	@echo "... heartbeat_pomo"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/CDC.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial0.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial1.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial2.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/HardwareSerial3.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/IPAddress.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/PluggableUSB.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Tone.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/USBCore.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WInterrupts.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WMath.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/abi.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/hooks.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/main.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/new.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_analog.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_digital.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_pulse.s"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.obj"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.i"
	@echo "... Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/wiring_shift.s"
	@echo "... headway_demo.obj"
	@echo "... headway_demo.i"
	@echo "... headway_demo.s"
	@echo "... neopixel/Adafruit_NeoPixel.obj"
	@echo "... neopixel/Adafruit_NeoPixel.i"
	@echo "... neopixel/Adafruit_NeoPixel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

